# Generated by Django 4.1 on 2023-11-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_full_name_customuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='organizer',
            field=models.BooleanField(default=False),
        ),
    ]
