# Generated by Django 4.1 on 2023-11-03 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_organizer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-email']},
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='insta',
            new_name='instagram',
        ),
    ]
